### 设二次多项式拟合函数为

$$s(x) = a_0 + a_1 x + a_2x^2$$

### 记$\varphi_0(x) = 1, \varphi_1(x) = x, \varphi_2(x) = x^2$， 并取权$w_i = 1$

In [8]:
def inner_product_varphi0_varphi0(x, y):
    sum = 0
    for i in range(8):
        sum += 1 * 1

    return sum


def inner_product_varphi0_varphi1(x, y):
    sum = 0
    for i in range(8):
        sum += x[i] * 1

    return sum

def inner_product_varphi0_varphi2(x, y):
    sum = 0
    for i in range(8):
        sum += x[i]**2  * 1

    return sum



def inner_product_varphi1_varphi0(x, y):
    sum = 0
    for i in range(8):
        sum += x[i] * 1

    return sum

def inner_product_varphi1_varphi1(x, y):
    sum = 0
    for i in range(8):
        sum += x[i] * x[i]

    return sum


def inner_product_varphi1_varphi2(x, y):
    sum = 0
    for i in range(8):
        sum += x[i] * x[i]**2

    return sum


def inner_product_varphi2_varphi0(x, y):
    sum = 0
    for i in range(8):
        sum += x[i]**2 * 1

    return sum


def inner_product_varphi2_varphi1(x, y):
    sum = 0
    for i in range(8):
        sum += x[i]**2 * x[i]

    return sum

def inner_product_varphi2_varphi2(x, y):
    sum = 0
    for i in range(8):
        sum += x[i]**2 * x[i]**2

    return sum

def inner_product_f_varphi0(x, y):
    sum = 0
    for i in range(8):
        sum += y[i] * 1

    return sum

def inner_product_f_varphi1(x, y):
    sum = 0
    for i in range(8):
        sum += y[i] * x[i]

    return sum

def inner_product_f_varphi2(x, y):
    sum = 0
    for i in range(8):
        sum += y[i] * x[i]**2

    return sum



x = [1, 1, 2, 3, 3, 3, 4, 5]
y = [4, 4, 4.5, 6, 6, 6, 8, 8.5]

# x = [0.2, 0.5, 0.7, 0.85, 1]
# y = [1.221, 1.649, 2.014, 2.340, 2.718]

print(f"(varphi_0, varphi_0)的内积结果: {inner_product_varphi0_varphi0(x, y)}")
print(f"(varphi_0, varphi_1)的内积结果: {inner_product_varphi0_varphi1(x, y)}")
print(f"(varphi_0, varphi_2)的内积结果: {inner_product_varphi0_varphi2(x, y)}")
print(f"(varphi_1, varphi_0)的内积结果: {inner_product_varphi1_varphi0(x, y)}")
print(f"(varphi_1, varphi_1)的内积结果: {inner_product_varphi1_varphi1(x, y)}")
print(f"(varphi_1, varphi_2)的内积结果: {inner_product_varphi1_varphi2(x, y)}")
print(f"(varphi_2, varphi_0)的内积结果: {inner_product_varphi2_varphi0(x, y)}")
print(f"(varphi_2, varphi_1)的内积结果: {inner_product_varphi2_varphi1(x, y)}")
print(f"(varphi_2, varphi_2)的内积结果: {inner_product_varphi2_varphi2(x, y)}")

print(f"(f, varphi_0)的内积结果: {inner_product_f_varphi0(x, y)}")
print(f"(f, varphi_1)的内积结果: {inner_product_f_varphi1(x, y)}")
print(f"(f, varphi_2)的内积结果: {inner_product_f_varphi2(x, y)}")

(varphi_0, varphi_0)的内积结果: 8
(varphi_0, varphi_1)的内积结果: 22
(varphi_0, varphi_2)的内积结果: 74
(varphi_1, varphi_0)的内积结果: 22
(varphi_1, varphi_1)的内积结果: 74
(varphi_1, varphi_2)的内积结果: 280
(varphi_2, varphi_0)的内积结果: 74
(varphi_2, varphi_1)的内积结果: 280
(varphi_2, varphi_2)的内积结果: 1142
(f, varphi_0)的内积结果: 47.0
(f, varphi_1)的内积结果: 145.5
(f, varphi_2)的内积结果: 528.5


### 可得法方程

In [9]:
import numpy as np

A = np.array([[8, 22, 74], [22, 74, 280], [74, 280, 1142]])
b = np.array([47.0, 145.50, 528.5])

# A = np.array([[5, 3.25, 2.5025], [3.25, 2.5025, 2.0901249999999996], [2.5025, 2.0901249999999996, 1.8262062499999998]])
# b = np.array([9.942, 7.185499999999999, 5.856599999999999])

alpha = np.linalg.solve(A, b)
print(f"系数矩阵A为： \n {A}")
print(f"b为： {b}")
print(f"解得alpha： {alpha}")


系数矩阵A为： 
 [[   8   22   74]
 [  22   74  280]
 [  74  280 1142]]
b为： [ 47.  145.5 528.5]
解得alpha： [3.00462963 0.81018519 0.06944444]


### 因此二次拟合多项式为：

$$S^*(x) = 3.00462963 + 0.81018519x + 0.06944444x^2$$
